server:
  port: 8765

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: create_exam
          uri: lb://EXAM
          predicates:
            - Path=/api/exam/**
            - Method=GET
#          filters:
#            - AuthenticationFilter

        - id: get_math_questions
          uri: lb://MATH
          predicates:
            - Path=/api/math/**
            - Method=GET
#          filters:
#            - AuthenticationFilter

        - id: get_history_questions
          uri: lb://HISTORY
          predicates:
            - Path=/api/history/**
            - Method=GET
#          filters:
#            - AuthenticationFilter

        - id: post_history_question
          uri: lb://HISTORY
          predicates:
            - Path=/api/history/**
            - Method=POST
#          filters:
#            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH
          predicates:
            - Path=/api/auth/**
