server:
  port: 8765

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true
      routes:
        - id: create_exam
          uri: lb://EXAM/api
          predicates:
            - Path=/exam
            - Method=GET
