server:
  port: 8765

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
        routes:
          - id: create_exam
            uri: lb://EXAM
            predicates:
              - Path=/api/exam
              - Method=GET
          - id:
