server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    username: nikita
    password: nikita
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true