server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    username: nikita
    password: nikita
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:db_tests/demo_data.sql
